### ISSUE TITLE
findup-sync is not in package.json

### ISSUE THREAD

**Issue by jbcpollak** [mateodelnorte/get-meta-file#1]
Trying to use meta-npm, I get an error `Error: Cannot find module 'findup-sync'`. This appears to be because it is not listed as a dependency in package.json of this project.

```
❯ meta
{ Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jpollak/src/6river/mfp-js/node_modules/get-meta-file/index.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
```

All I did to reproduce this was start with a fresh meta repo and run:
```
> npm i -D meta-npm
> meta
```

**Comment by mateodelnorte** [comment]
Yup. Sorry about that! All fixed now. `npm uninstall -g meta && npm i -g meta` and you should be good. If you've got `meta-npm` as one of your meta project's devDependencies, bump the version to `0.0.22`.

**Comment by jbcpollak** [comment]
Confirmed its fixed, thanks for the rapid response.

**Comment by mateodelnorte** [comment]
You got it! Thanks for using meta!

Feel free to reach out on nycnode.com/slack to give feedback or suggest new
features!
